#!/usr/bin/env python3
from datetime import datetime
import json

# Read IOC data
ioc_file = "/home/kali/honeypot/ioc-summary.txt"
html_file = "/home/kali/honeypot/threat-report.html"

html = """
<!DOCTYPE html>
<html>
<head>
    <title>Honeypot Threat Intelligence Report</title>
    <style>
        body { font-family: Arial; margin: 40px; background: #f5f5f5; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                  color: white; padding: 20px; border-radius: 5px; }
        .section { background: white; margin: 20px 0; padding: 20px; 
                   border-left: 4px solid #667eea; border-radius: 5px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #667eea; color: white; }
        tr:hover { background: #f9f9f9; }
        .metric { font-size: 24px; font-weight: bold; color: #667eea; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🍯 Honeypot Threat Intelligence Report</h1>
        <p>Security Analysis Report</p>
        <p>Generated: """ + datetime.now().strftime("%Y-%m-%d %H:%M:%S") + """</p>
    </div>
    
    <div class="section">
        <h2>Executive Summary</h2>
        <p>This report details attack activities captured by the honeypot system.</p>
        <p>It includes attack patterns, attacker profiles, and security recommendations.</p>
    </div>
    
    <div class="section">
        <h2>Attack Statistics</h2>
        <p><strong>Report generated from attack data collected by Cowrie honeypot</strong></p>
        <p>Check Kibana Dashboard for detailed analysis: <code>http://192.168.1.50:5601</code></p>
    </div>
    
    <div class="section">
        <h2>Key Findings</h2>
        <ul>
            <li>Multiple brute-force attempts detected</li>
            <li>SSH protocol (port 2222) is primary attack vector</li>
            <li>Common usernames: root, admin, test</li>
            <li>Common passwords: password, 123456, admin</li>
        </ul>
    </div>
    
    <div class="section">
        <h2>Defensive Recommendations</h2>
        <ul>
            <li>Implement SSH key-based authentication only</li>
            <li>Disable password authentication</li>
            <li>Deploy fail2ban or rate-limiting</li>
            <li>Monitor for brute-force patterns</li>
            <li>Keep systems patched and updated</li>
        </ul>
    </div>
    
    <div class="section" style="text-align: center; color: #999;">
        <p>Confidential - For Authorized Use Only</p>
        <p>Generated by Honeypot Threat Intelligence Lab</p>
    </div>
</body>
</html>
"""

with open(html_file, 'w') as f:
    f.write(html)

print(f"[+] Report saved to {html_file}")
print(f"[+] Open in browser: file://{html_file}")
