input {
  file {
    path => "/var/log/cowrie/log/*"
    type => "cowrie"
    start_position => "beginning"
    codec => json
  }
}
filter {
  if [type] == "cowrie" {
    mutate {
      add_field => { "[@metadata][index_name]" => "cowrie-%{+YYYY.MM.dd}" }
    }
  }
}
output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][index_name]}"
  }
}
